controller_manager:
  ros__parameters:
    update_rate: 100  # Hz

    joint_trajectory_controller:
      type: joint_trajectory_controller/JointTrajectoryController

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

joint_trajectory_controller:
  ros__parameters:
    joints:
      - world_to_follower_x
      - follower_x_to_follower_y
      - follower_y_to_follower_z
      - follower_z_to_follower_yaw
      - follower_yaw_to_follower_pitch
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity